version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'RevendaVeiculos.Rabbit'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  revenda-veiculos-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: 'RevendaVeiculos.SqlServer'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "revenda#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data

  revendaveiculos.message:
    image: ${DOCKER_REGISTRY-}revendaveiculosmessage
    container_name: 'RevendaVeiculos.Message'
    build:
      context: .
      dockerfile: RevendaVeiculos.Message/Dockerfile

  revendaveiculos.web:
    image: ${DOCKER_REGISTRY-}revendaveiculosweb
    container_name: 'RevendaVeiculos.Web'
    build:
      context: .
      dockerfile: RevendaVeiculos.Web/Dockerfile
    environment:
      DbServer: "host.docker.internal"
      DbPort: "1433"
      DbUser: "sa"
      Password: "revenda#2021"
      Database: "RevendaVeiculos"

networks:
  rabbitmq_go_net:
    driver: bridge